<?php

return [
    'environment' => 'production',
    'base_url' => '',
    'base_url_production' => 'https://api.forte.net/v3',
    'base_url_sandbox' => 'https://sandbox.forte.net/api/v3',
    'js_url' => '',
    'js_url_production' => 'https://api.forte.net/js/v1',
    'js_url_sandbox' => 'https://sandbox.forte.net/api/js/v1',
    'pg_action_url' => '',
    'pg_action_url_production' => 'https://www.paymentsgateway.net/cgi-bin/postauth.pl',
    'pg_action_url_sandbox' => 'https://www.paymentsgateway.net/cgi-bin/posttest.pl',
    'swp_base_url' => '',
    'swp_base_url_production' => 'https://swp.paymentsgateway.net',
    'swp_base_url_sandbox' => 'https://sandbox.paymentsgateway.net/swp',
    'organization_id' => 'org_xxxxx',
    'location_id' => 'loc_xxxxx',
    'api_access_id' => 'YOUR_API_ACCESS_ID',
    'api_secure_key' => 'YOUR_API_SECURE_KEY',
    'api_login_id' => 'YOUR_API_LOGIN_ID',
    'secure_transaction_key' => 'YOUR_SECURE_TRANSACTION_KEY',
    'secure_transaction_keys' => [
        'default' => 'YOUR_SECURE_TRANSACTION_KEY',
        'fco_james' => 'YOUR_SECURE_TRANSACTION_KEY',
        'fco_v1' => 'YOUR_SECURE_TRANSACTION_KEY',
        'soap_hash' => 'YOUR_SECURE_TRANSACTION_KEY',
        'swp_embedded_charge' => 'YOUR_SECURE_TRANSACTION_KEY',
        'swp_embedded_capture' => 'YOUR_SECURE_TRANSACTION_KEY',
        'swp_redirect_full' => 'YOUR_SECURE_TRANSACTION_KEY',
        'goob' => 'YOUR_SECURE_TRANSACTION_KEY',
        'hernan_v1' => 'YOUR_SECURE_TRANSACTION_KEY',
    ],
    'pg_password' => 'YOUR_PG_PASSWORD',
    'pg_merchant_id' => 'YOUR_PG_MERCHANT_ID',
    'merchant_ids' => [
        'default' => 'YOUR_PG_MERCHANT_ID',
        'soap_hash' => 'YOUR_PG_MERCHANT_ID',
    ],
    'pg_payment_token' => 'YOUR_PG_PAYMENT_TOKEN',
    'pg_customer_token' => 'YOUR_PG_CUSTOMER_TOKEN',
    'freshdesk_api_key' => 'YOUR_FRESHDESK_API_KEY',
    'freshdesk_domain' => 'YOUR_FRESHDESK_DOMAIN',
    'freshdesk_password' => 'YOUR_FRESHDESK_PASSWORD',
    'html2pdf_api_key' => 'YOUR_HTML2PDF_API_KEY',
    'credential_groups' => [
        'rest' => [
            'working' => [],
            'partial' => [],
            'not_working' => [],
        ],
        'swp' => [
            'working' => [],
            'partial' => [],
            'not_working' => [],
        ],
        'soap' => [
            'working' => [],
            'partial' => [],
            'not_working' => [],
        ],
        'agi' => [
            'working' => [],
            'partial' => [],
            'not_working' => [],
        ],
    ],
];
